#pragma once

enum EScriptingArgumentType
{
	SCRIPTING_ARG_UNKNOWN,
	SCRIPTING_ARG_BOOLEAN,
	SCRIPTING_ARG_NUMBER,
	SCRIPTING_ARG_STRING,
	SCRIPTING_ARG_NULL,
	SCRIPTING_ARG_TABLE_OR_ARRAY,
	SCRIPTING_ARG_FUNCTION
};